# Generated by Django 6.1 on 2026-08-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Conference', 'Conference'), ('Meeting', 'Meeting')], max_length=50)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('Engineering', 'Engineering'), ('Business', 'Business'), ('Arts', 'Arts'), ('Science', 'Science')], max_length=50)),
                ('academic_year', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=20)),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('registrations', models.PositiveIntegerField(default=0)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('completion', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback_rating', models.FloatField(blank=True, null=True)),
                ('feedback_responses', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('name', 'event_date', 'department')},
            },
        ),
    ]
